# .streamlit/secrets.toml

[mysql]
dialect = "mysql"
RDS_HOST = "database-dentist.cx6cggcw84g9.eu-west-2.rds.amazonaws.com"
RDS_PORT = 3306
RDS_DB = "dentist_information"
RDS_USER = "admin"
RDS_PASSWORD = "kcladmin"
RDS_CHARTSET = "utf8mb4"
